## wine quality detection using multilayer perceptron model

In [1]:
import pandas as pd

In [2]:
data1=pd.read_csv("wine-red.csv")       ### downloaded from uci machine learning repository

In [3]:
data2=pd.read_csv("wine-white.csv")

In [4]:
data1.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [5]:
data2.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [6]:
data1.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
from sklearn.preprocessing import StandardScaler
import numpy as np

In [9]:
X=data1.iloc[:,:-1]

In [10]:
X.fillna(X.mean(),inplace=True)

In [11]:
Y=data1['quality']

In [12]:
Y.fillna(Y.mean(),inplace=True)

In [13]:
scaler=StandardScaler()

In [14]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [15]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((1279, 11), (320, 11), (1279,), (320,))

In [16]:
scaler.fit(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [17]:
X_train = scaler.transform(x_train)
X_test = scaler.transform(x_test)

## training model

In [18]:
from sklearn.neural_network import MLPClassifier

In [19]:
mlp=MLPClassifier(hidden_layer_sizes=(512,256,128,64,32,16))

In [20]:
mlp.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(512, 256, 128, 64, 32, 16),
       learning_rate='constant', learning_rate_init=0.001, max_iter=200,
       momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
       power_t=0.5, random_state=None, shuffle=True, solver='adam',
       tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [21]:
pred=mlp.predict(X_test)

In [22]:
pred

array([5, 4, 7, 5, 5, 6, 5, 6, 5, 6, 5, 5, 6, 6, 5, 6, 7, 5, 5, 5, 6, 5,
       6, 6, 6, 5, 5, 7, 5, 6, 6, 5, 6, 5, 7, 7, 6, 6, 7, 7, 6, 7, 7, 7,
       6, 5, 5, 6, 6, 6, 5, 6, 6, 6, 6, 5, 5, 5, 7, 5, 5, 6, 6, 6, 5, 6,
       5, 5, 7, 6, 5, 5, 4, 5, 6, 6, 5, 5, 5, 7, 5, 6, 6, 6, 6, 6, 7, 5,
       7, 5, 5, 6, 7, 5, 7, 5, 6, 5, 5, 5, 7, 6, 6, 6, 5, 4, 5, 6, 6, 5,
       6, 5, 8, 5, 6, 6, 6, 7, 6, 6, 5, 6, 5, 5, 8, 7, 5, 5, 5, 7, 6, 5,
       6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 5, 5, 5, 6, 8, 6, 5, 5, 5, 5, 6, 6,
       6, 6, 5, 6, 6, 7, 5, 6, 6, 5, 5, 5, 6, 6, 6, 6, 5, 5, 5, 7, 4, 6,
       5, 8, 7, 5, 5, 7, 6, 7, 7, 6, 6, 6, 5, 5, 6, 5, 6, 6, 5, 5, 5, 4,
       6, 5, 5, 7, 6, 6, 5, 5, 5, 6, 6, 6, 5, 7, 5, 7, 5, 6, 5, 6, 6, 5,
       5, 6, 6, 6, 7, 6, 6, 6, 5, 6, 6, 6, 5, 5, 6, 6, 5, 7, 7, 6, 6, 5,
       5, 5, 7, 5, 7, 5, 5, 6, 6, 4, 5, 5, 5, 5, 5, 5, 5, 7, 5, 6, 6, 5,
       5, 5, 4, 5, 5, 6, 5, 5, 6, 6, 7, 6, 6, 6, 6, 7, 5, 6, 5, 6, 6, 6,
       5, 5, 7, 6, 5, 4, 6, 6, 6, 6, 6, 5, 5, 6, 6,

In [23]:
from sklearn.metrics import classification_report,confusion_matrix

In [24]:
confusion_matrix(y_test,pred)

array([[ 0,  0,  2,  0,  0,  0],
       [ 0,  1,  4,  4,  2,  0],
       [ 0,  6, 92, 31,  6,  0],
       [ 0,  1, 35, 89, 16,  1],
       [ 0,  0,  1,  8, 15,  3],
       [ 0,  0,  0,  1,  2,  0]], dtype=int64)

In [25]:
import warnings
warnings.filterwarnings('ignore')

In [26]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.12      0.09      0.11        11
           5       0.69      0.68      0.68       135
           6       0.67      0.63      0.65       142
           7       0.37      0.56      0.44        27
           8       0.00      0.00      0.00         3

   micro avg       0.62      0.62      0.62       320
   macro avg       0.31      0.33      0.31       320
weighted avg       0.62      0.62      0.62       320



In [27]:
##weight matrices
mlp.coefs_

[array([[ 0.11217701,  0.03996579,  0.10003313, ...,  0.03642785,
          0.03135723, -0.00741585],
        [-0.0998345 ,  0.04950461,  0.10530516, ...,  0.13913658,
         -0.06294232, -0.04168953],
        [-0.1348333 , -0.10520531, -0.0563053 , ..., -0.14065364,
         -0.16868035, -0.05553891],
        ...,
        [ 0.10551751,  0.12008246,  0.0909618 , ..., -0.10129975,
         -0.05783945, -0.01973557],
        [ 0.07863866,  0.0956684 , -0.18368915, ...,  0.13521258,
         -0.04054133, -0.15640599],
        [-0.04388558, -0.01186867, -0.05491374, ..., -0.05493402,
         -0.0124348 ,  0.07595419]]),
 array([[ 0.07013858, -0.02438633, -0.06107529, ..., -0.0540854 ,
         -0.07893391, -0.07618079],
        [-0.10949057,  0.17493621, -0.12374803, ..., -0.02823335,
          0.02905934,  0.08077804],
        [-0.21714664,  0.04201436, -0.02315373, ..., -0.05167857,
          0.03858543, -0.02887627],
        ...,
        [-0.0371381 , -0.02815536,  0.025966  , ..., -

In [28]:
### biases
mlp.intercepts_

[array([-0.02908083, -0.07418468,  0.02137329,  0.07990032,  0.0450437 ,
        -0.13617851,  0.06596612, -0.07959678, -0.09686222,  0.0321616 ,
        -0.02547534,  0.01364815, -0.12043869,  0.04095727,  0.07324243,
         0.10822553, -0.1189585 , -0.02052293, -0.06540971,  0.01514833,
        -0.05948823, -0.07804879,  0.10335738,  0.06953226,  0.10608083,
         0.09995177, -0.10171298,  0.02417198,  0.12003307, -0.03356208,
         0.02430227, -0.0513085 ,  0.04164005,  0.08434212,  0.05895334,
         0.04766674, -0.09959304,  0.02889717, -0.04915519, -0.00853897,
        -0.09508544, -0.06682164,  0.03570553, -0.01389475,  0.05468319,
         0.05271321,  0.09958707,  0.04824516,  0.02890991,  0.04434993,
         0.02643141, -0.02350255, -0.06614776, -0.02795378, -0.06486441,
         0.15456866, -0.0567401 ,  0.09193111, -0.03914651, -0.07628724,
        -0.08027573,  0.04900612, -0.05819055,  0.13193454,  0.13617403,
        -0.09836105,  0.14319947, -0.00072502,  0.0

In [29]:
len(mlp.coefs_[0])


11

In [30]:
len(mlp.intercepts_[0])

512